-- Este ficheiro foi substituído pelo fluxo oficial de migrações.
-- Fonte de verdade do schema: supabase/migrations/
--
-- Ver: supabase/migrations/20260419120000_carteira_membro_schema.sql
-- Integração GitHub: ligue o repositório no painel Supabase e use a pasta supabase/,
-- ou aplique migrações com a CLI: supabase db push (ver .github/workflows/supabase-db.yml).
